[tool.poetry]
name = "practice03-07"
version = "0.1.0"
description = ""
authors = ["JulianBSL <julianbsanchezlopez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.8"
rasa = "^3.6.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
