[tool.poetry]
name = "mislata"
version = "0.1.0"
description = ""
authors = ["Ana Jimenez"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.8.0"
scikit-learn = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
