# Tarea: Modificar el docker-compose.yml para incluir un volumen que persista los datos de

version: '3.1'

services:
  # Servicio Web:
  # - Utiliza la imagen construida en la Parte 1.
  # - Mapea el puerto 3000 al puerto 3000 del host.
  # - Conecta a la red app-network.
  web:
    build: ./../Exercise01
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Servicio Redis:
  # - Utiliza la imagen redis:alpine.
  # - No necesita mapeo de puertos.
  # - Conecta a la misma red app-network.
  # - Monta este volumen en /data dentro del contenedor de Redis.
  redis:
    image: redis:alpine
    networks:
      - app-network
    volumes:
      - redis-data:/data

# Redes:
# - Define app-network como una red de tipo bridge.
networks:
  app-network:
    driver: bridge

# Volumen:
# - Define un volumen llamado redis-data para persistir los datos de Redis.
volumes:
  redis-data:
    driver: local
